### PR TITLE
Updated the services and interfaces

### PR DESCRIPTION
**Pull request by matlalatk97**
I've updated the services and interfaces.

As stated on whatsapp further changes to the services will be added tomorrow pertaining to the front-end as well so that components can depend on the services

### CODE REVIEW

**Comment by tshegomotlatle** [comment]
@matlalatk97 please check the CI build, you have failing tests.

**Comment by matlalatk97** [comment]
Can you include a snippet ? 

Code runs fine on my end. I haven't hooked up the services yet so they shouldn't interfere with any existing functionality. Did you do an "npm install" to update the dependencies ?

**Comment by tshegomotlatle** [comment]
Check the details where it says CI/Build on this page. or go to github actions. the issue seems to be your unit tests

**Comment by matlalatk97** [comment]
Seems like the bulk of the tests are unrelated to what I was working on. 99% of them allude to the NgModal and inputs as well as Navbar elements.  And the 5 files I've modified are completely unrelated.

I'll try workaround it

**Review by tshegomotlatle — APPROVED** [review]

**Pull request merged**
